### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by oliver-la** [cybrox/crunchdb#1]
Would be great, if you could add your project to the packagist repository.
https://packagist.org/

Thanks!

**Comment by cybrox** [comment]
The library should now be available via [packagist](https://packagist.org/packages/cybrox/crunchdb)

Feedback as to if it is actually working the way you expected it to is appreciated, I'm way out the loop on the PHP ecosystem by now 😷

**Comment by oliver-la** [comment]
Thanks a bunch and sorry for my late reply!
Does not quite work yet, but I fixed it already for you: https://github.com/cybrox/crunchdb/pull/2

Also: is there a way for you to change the stability of your package?

I get the following error when I try to install the package as ``stable``:

> $ php composer.phar require cybrox/crunchdb
> Could not find package cybrox/crunchdb at any version for your minimum-stab  
>   ility (stable). Check the package spelling or your minimum-stability    

Instead, I have to install it this way and it's not pretty. :/

`php composer.phar require cybrox/crunchdb:dev-master@dev`

**Comment by cybrox** [comment]
Sure thing, thanks for the PR!

Yeah, I released the new version as `3.1.0` since capitalizing class names is a breaking change. Looks like pakagist does not parse tags without minor version as versions at all. Anyways, you should now be able to install `3.1.0` with `>= 0.0.0` or ideally `~> 3.1.0`

Let me know if you run into any additional problems :)
